services:
  factorio:
    image: debian@sha256:9cc080028c43b27d2074d63a5f9caf7166d731494965616c1a6d2827a004585c
    container_name: factorio
    restart: always
    user: 1000:1000
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./data:/factorio
      - ./server-settings.json:/factorio/data/server-settings.json
      - ./player-data.json:/factorio/player-data.json
    command:
      - /factorio/bin/x64/factorio
      - --start-server
      - /factorio/local.zip
      - --server-settings
      - /factorio/data/server-settings.json
    environment:
      TZ: "Asia/Singapore"
