services:
  factorio:
    image: debian@sha256:34cd9e9fd437c0a095ec39cb2e73422c9f30821b0d0848ed74fd0d43bae4d958
    container_name: factorio
    restart: always
    user: 1000:1000
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./data:/factorio
      - ./server-settings.json:/factorio/data/server-settings.json
      - ./player-data.json:/factorio/player-data.json
    command:
      - /factorio/bin/x64/factorio
      - --start-server
      - /factorio/local.zip
      - --server-settings
      - /factorio/data/server-settings.json
    environment:
      TZ: "Asia/Singapore"
