services:
  factorio:
    image: debian@sha256:35b8ff74ead4880f22090b617372daff0ccae742eb5674455d542bef71ef1999
    container_name: factorio
    restart: always
    user: 1000:1000
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./data:/factorio
    command:
      - /factorio/bin/x64/factorio
      - --start-server
      - /factorio/local.zip
      - --server-settings
      - /factorio/data/server-settings.json
    environment:
      TZ: "Asia/Singapore"
