services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main@sha256:bb3f0281554bf05a9d505ffb5a5f067ab53e13ac772eb4ea3077a92ddc64600e
    container_name: open-webui
    restart: always
    volumes:
      - ./data:/app/backend/data
    environment:
      CUSTOM_NAME: AI Chat
    networks:
      - open-webui
    labels:
      traefik.enable: true
      traefik.docker.network: core_open-webui
      homepage.group: Services
      homepage.name: Open WebUI
      homepage.icon: open-webui
      homepage.href: &url https://open-webui.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  open-webui:
