services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main@sha256:a6da0c292081d810a396ce786a10536d0b1b9ba2925dcca20ebb03f9fa90dbff
    container_name: open-webui
    restart: always
    volumes:
      - ./data:/app/backend/data
    environment:
      CUSTOM_NAME: AI Chat
    networks:
      - open-webui
    labels:
      traefik.enable: true
      traefik.docker.network: core_open-webui
      homepage.group: Services
      homepage.name: Open WebUI
      homepage.icon: open-webui
      homepage.href: &url https://open-webui.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  open-webui:
