services:
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium@sha256:ba9fb80100147d657c6fbffadf95308f6843c6931d3e064ac2fb612282101f8e
    restart: always
    environment:
      TZ: Asia/Singapore
      TOKEN: ${BROWSERLESS_TOKEN}

      # The following are necessary for link previews to work
      CORS: true
    networks:
      - changedetection-io
      - karakeep
      - reactive-resume

      # External
      - polythought

networks:
  polythought:
    external: true
    name: polythought_polythought
