services:
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium@sha256:ae07025606e03c9b263620aaf4d09c52728f71a104ac7d471a68c23dec72c05f
    restart: always
    environment:
      TZ: Asia/Singapore
      TOKEN: ${BROWSERLESS_TOKEN}

      # The following are necessary for link previews to work
      CORS: true
    networks:
      - changedetection-io
      - karakeep
      - reactive-resume
      - open-webui

      # External
      - polythought

networks:
  polythought:
    external: true
    name: polythought_polythought
