services:
  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium@sha256:a6d37fbe2f5606e5653fd99f0c48ae313b1430eb59c6e252ad8904fc755aaac5
    restart: always
    environment:
      TZ: Asia/Singapore
      TOKEN: ${BROWSERLESS_TOKEN}

      # The following are necessary for link previews to work
      CORS: true
    networks:
      - changedetection-io
      - karakeep
      - reactive-resume

      # External
      - polythought

networks:
  polythought:
    external: true
    name: polythought_polythought
