services:
  metabase:
    image: metabase/metabase:latest@sha256:98ce8b44f0fe2929e267c7c19df5e54001ca8bff40ffa43a54b806a89e107757
    container_name: metabase
    restart: always
    volumes:
      - /dev/urandom:/dev/random:ro
      - ../backend:/db/backend:ro # Literature
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: metabase-db
      MB_DB_PORT: 5432
      MB_DB_DBNAME: metabaseappdb
      MB_DB_USER: postgres
      MB_DB_PASS: ${MB_DB_PASS}
    depends_on:
      - metabase-db
    networks:
      - metabase
    labels:
      traefik.enable: true
      traefik.docker.network: core_metabase
      homepage.group: Services
      homepage.name: Metabase
      homepage.icon: metabase
      homepage.href: &url https://metabase.nicholaslyz.com
      homepage.siteMonitor: *url

  metabase-db:
    image: postgres:18@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
    restart: always
    container_name: metabase-db
    networks:
      - metabase
    environment:
      POSTGRES_DB: metabaseappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MB_DB_PASS}
    volumes:
      - ./data:/var/lib/postgresql

networks:
  metabase:
