services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4
    restart: always
    user: 1000:1000
    environment:
      TZ: Asia/Singapore
    volumes:
      - /mnt/storage/Audio/Audiobooks:/audiobooks
      - /mnt/storage/Audio/Podcasts:/podcasts
      - ./data/config:/config
      - ./data/metadata:/metadata
    networks:
      - audiobookshelf
    labels:
      traefik.enable: true
      traefik.docker.network: core_audiobookshelf
      homepage.group: Services
      homepage.name: Audiobookshelf
      homepage.icon: audiobookshelf
      homepage.href: &url https://audiobookshelf.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: audiobookshelf
      homepage.widget.url: *url
      homepage.widget.key: ${API_KEY}

networks:
  audiobookshelf:
