services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest@sha256:35b089054ac9b4257976107e71673d9e30ac17c9b50bbf8b4783f2f6d1d1981f
    restart: always
    user: 1000:1000
    volumes:
      - ./data:/etc/searxng/
      - core-data:/var/cache/searxng/
    networks:
      # This is used purely as a cheap search backend for Hermes/Open WebUI.
      # To fallback to Serper/Tavily if this gets blocked in the future.
      - searxng
      - hermes-agent-xiaoyun
      - hermes-agent-gdfm
      - open-webui

volumes:
  core-data:

networks:
  searxng:
