services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest@sha256:75e85884da87a717655d6313421c8fb42aede84219b06873311179ae830ab396
    restart: always
    user: 1000:1000
    volumes:
      - ./data:/etc/searxng/
      - core-data:/var/cache/searxng/
    networks:
      # This is used purely as a cheap search backend for Hermes/Open WebUI.
      # To fallback to Serper/Tavily if this gets blocked in the future.
      - searxng
      - hermes-agent-xiaoyun
      - hermes-agent-gdfm
      - open-webui

volumes:
  core-data:

networks:
  searxng:
