services:
  vector:
    image: timberio/vector:0.58.0-debian@sha256:1c1ea358c617ea0b23003d5af87f7a678b30f8f7096437e680380c47fc13d2d9
    container_name: vector
    restart: always
    networks:
      - vector
    volumes:
      - ./vector.yml:/etc/vector/vector.yaml
      - ./data:/var/lib/vector # file checkpoints, internal state, disk buffers when sinks are unavailable
      - /var/run/docker.sock:/var/run/docker.sock:ro # For docker logs
      - /var/log/journal:/hostfs/var/log/journal:ro # For journald logs
    environment:
      TZ: Asia/Singapore

networks:
  vector:
