services:
  vector:
    image: timberio/vector:0.56.0-debian@sha256:93b072b416fd29152f1bfe5bd2925a0b48999aeb069f3ae000691f82a135c200
    container_name: vector
    restart: always
    networks:
      - vector
    volumes:
      - ./vector.yml:/etc/vector/vector.yaml
      - ./data:/var/lib/vector # file checkpoints, internal state, disk buffers when sinks are unavailable
      - /var/run/docker.sock:/var/run/docker.sock:ro # For docker logs
      - /var/log/journal:/hostfs/var/log/journal:ro # For journald logs
    environment:
      TZ: Asia/Singapore

networks:
  vector:
