services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf@sha256:b5b9e400c086e5334a4947a0d7cd589808f743f29267d7f41c18200cf4bc48b4
    restart: always
    environment:
      SECURITY_ENABLELOGIN: true
      DISABLE_ADDITIONAL_FEATURES: false
    networks:
      - stirling-pdf
    volumes:
      - ./data/configs:/configs
    labels:
      traefik.enable: true
      traefik.docker.network: core_stirling-pdf
      homepage.group: Services
      homepage.name: Stirling PDF
      homepage.icon: stirling-pdf
      homepage.href: https://stirling-pdf.nicholaslyz.com
      homepage.siteMonitor: http://stirling-pdf:8080

networks:
  stirling-pdf:
