services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf@sha256:7ed4d9681d18e4fbc3aa6a63647c4b5c2bcc4b75841df7c05d7e3d2320f5c9a1
    restart: always
    environment:
      SECURITY_ENABLELOGIN: true
      DISABLE_ADDITIONAL_FEATURES: false
    networks:
      - stirling-pdf
    volumes:
      - ./data/configs:/configs
    labels:
      traefik.enable: true
      traefik.docker.network: core_stirling-pdf
      homepage.group: Services
      homepage.name: Stirling PDF
      homepage.icon: stirling-pdf
      homepage.href: https://stirling-pdf.nicholaslyz.com
      homepage.siteMonitor: http://stirling-pdf:8080

networks:
  stirling-pdf:
