services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf@sha256:a6c5e627ceef6ed323a63da13e0d44ef68503320d1917cbc7ca2fd8e4a827aae
    restart: always
    environment:
      SECURITY_ENABLELOGIN: true
      DISABLE_ADDITIONAL_FEATURES: false
    networks:
      - stirling-pdf
    volumes:
      - ./data/configs:/configs
    labels:
      traefik.enable: true
      traefik.docker.network: core_stirling-pdf
      homepage.group: Services
      homepage.name: Stirling PDF
      homepage.icon: stirling-pdf
      homepage.href: https://stirling-pdf.nicholaslyz.com
      homepage.siteMonitor: http://stirling-pdf:8080

networks:
  stirling-pdf:
