services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest@sha256:56fc719962de84a2bb1033d6925c2796e62e6d59b6504698528dd08d2d5cbe15
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
    volumes:
      - ./data:/config
      - /mnt/storage/Notes:/Notes
      - /mnt/storage/Relationship:/Relationship
      - "/mnt/storage/Personal/Passport and ID Photos:/Passport and ID Photos"
      - "/mnt/storage/Memorial Folder/Elizabeth/Ophthalmology:/Elizabeth/Ophthalmology"
      - /mnt/storage/chanel:/chanel
    ports:
      # Required for devices without tailscale (e.g. Kindle)
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp #discovery broadcasts
    networks:
      - syncthing
    labels:
      traefik.http.routers.syncthing.rule: Host(`syncthing.internal.nicholaslyz.com`)
      traefik.http.routers.syncthing.entrypoints: tailscale
      traefik.enable: true
      traefik.docker.network: core_syncthing
      homepage.group: Services
      homepage.name: Syncthing
      homepage.icon: syncthing
      homepage.href: &url https://syncthing.internal.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  syncthing:
