services:
  calibre-web:
    container_name: calibre-web
    image: linuxserver/calibre-web@sha256:8dfec6e631dd6eb432a37f8a638f5a2b6e4a4927ce71e2b26bb82a1bb3a3ff15
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
      DOCKER_MODS: linuxserver/mods:universal-calibre # Enable ebook conversion
    volumes:
      - /mnt/storage/Books:/library
      - ./data:/config
    networks:
      - calibre-web
    labels:
      traefik.enable: true
      traefik.docker.network: core_calibre-web
      homepage.group: Services
      homepage.name: Calibre Web
      homepage.icon: calibre-web
      homepage.href: &url https://calibre-web.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: calibreweb
      homepage.widget.url: *url
      homepage.widget.username: ${USERNAME}
      homepage.widget.password: ${PASSWORD}

networks:
  calibre-web:
