services:
  calibre-web:
    container_name: calibre-web
    image: linuxserver/calibre-web@sha256:204e20768d5d94cdb27d89958c520714e2c7b2850293c9d9e8f6340662bcc102
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
      DOCKER_MODS: linuxserver/mods:universal-calibre # Enable ebook conversion
    volumes:
      - /mnt/storage/Books:/library
      - ./data:/config
    networks:
      - calibre-web
    labels:
      traefik.enable: true
      traefik.docker.network: core_calibre-web
      homepage.group: Services
      homepage.name: Calibre Web
      homepage.icon: calibre-web
      homepage.href: &url https://calibre-web.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: calibreweb
      homepage.widget.url: *url
      homepage.widget.username: ${USERNAME}
      homepage.widget.password: ${PASSWORD}

networks:
  calibre-web:
