services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant@sha256:59aa8824955c9db491b75d2eebe42bd68494f80c2ec69ec0d66d9dae37d37514
    container_name: home-assistant
    restart: always
    depends_on:
      - mosquitto
      - frigate
    post_start:
      - command: udhcpc -i eth1 -x hostname:home-assistant # Get a DHCP address for itself
        user: root
    networks:
      home-assistant:
      home-assistant-macvlan:
        mac_address: 3a:bb:ab:31:7e:5c # Use a fixed MAC to prevent IP address exhaustion on container restarts
    volumes:
      - ./data/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: core_home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123
      homepage.group: Services
      homepage.name: Home Assistant
      homepage.icon: home-assistant
      homepage.href: &url https://home-assistant.nicholaslyz.com
      homepage.siteMonitor: *url
    cap_add:
      - net_admin # Allow HA to discover devices on the network

  music-assistant:
    image: ghcr.io/music-assistant/server@sha256:7c322702905d55a5cdc4ca2dcb4ea951150bd0169f81a09a30f0ac67b31f7285
    container_name: music-assistant
    restart: always
    networks:
      home-assistant:
      music-assistant-macvlan:
        mac_address: B2:13:B2:C2:30:53 # Use a fixed MAC to prevent IP address exhaustion on container restarts
    post_start:
      - command: /bin/bash -c 'apt-get update && apt-get install -y udhcpc && udhcpc -i eth1 -x hostname:music-assistant' # Get a DHCP address for itself
        user: root
    volumes:
      - ./data/music-assistant:/data/
    labels:
      traefik.enable: true
      traefik.docker.network: core_home-assistant
      homepage.group: Services
      homepage.name: Music Assistant
      homepage.icon: music-assistant
      homepage.href: &url https://music-assistant.nicholaslyz.com
      homepage.siteMonitor: *url
    cap_add:
      - net_admin # Allow HA to discover devices on the network/obtain DHCP address

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt@sha256:f1f5195076d771727e9ff3db638de0f54d37969a66f317cd34624a7af5faf364
    restart: always
    user: 1000:1000
    networks:
      - zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: core_zigbee2mqtt
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.internal.nicholaslyz.com`)
      traefik.http.routers.zigbee2mqtt.entrypoints: tailscale
      homepage.group: Services
      homepage.name: Zigbee2MQTT
      homepage.icon: zigbee2mqtt
      homepage.href: https://zigbee2mqtt.internal.nicholaslyz.com
      homepage.siteMonitor: http://zigbee2mqtt:8080

  mosquitto:
    image: eclipse-mosquitto@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
    container_name: mosquitto
    restart: always
    user: 1000:1000
    # We don't create a mosquitto network, as that would allow cross-communication between
    # containers that use mosquitto.
    networks:
      - zigbee2mqtt
      - home-assistant
      - frigate
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data

networks:
  home-assistant:
  home-assistant-macvlan:
    # Required for device discovery
    # ipvlan does not support DHCP
    driver: macvlan
    driver_opts:
      parent: enp5s0
  music-assistant-macvlan:
    driver: macvlan
    driver_opts:
      parent: enp5s0

  zigbee2mqtt:
