
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant@sha256:8848691147f01a6eee7753de2ade21b04d6168fcd2e2a7089f6f84e3b7b86960
    container_name: home-assistant
    restart: always
    user: 1000:1000
    post_start:
      - command: udhcpc -i eth1 -x hostname:home-assistant
        user: root
    networks:
      home-assistant:
      home-assistant-macvlan:
        mac_address: 3a:bb:ab:31:7e:5c # Fix MAC to prevent IP address exhaustion on container restarts
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      traefik.enable: true
      traefik.docker.network: core_home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123
      homepage.group: Services
      homepage.name: Home Assistant
      homepage.icon: home-assistant
      homepage.href: &url https://home-assistant.nicholaslyz.com
      homepage.siteMonitor: *url
    cap_add:
      - net_admin

networks:
  home-assistant:
  home-assistant-macvlan:
    driver: macvlan # Required for device discovery
    driver_opts:
      parent: enp5s0
      # ipvlan does not support DHCP
