services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant@sha256:4c940155cfd5b0187a6faee2db5d52b98bb573edc1aeee95d0818bb17b6534d7
    container_name: home-assistant
    restart: always
    user: 1000:1000
    depends_on:
      - mosquitto
    post_start:
      - command: udhcpc -i eth1 -x hostname:home-assistant # Get a DHCP address for itself
        user: root
    networks:
      home-assistant:
      home-assistant-macvlan:
        mac_address: 3a:bb:ab:31:7e:5c # Use a fixed MAC to prevent IP address exhaustion on container restarts
    volumes:
      - ./data/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: core_home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123
      homepage.group: Services
      homepage.name: Home Assistant
      homepage.icon: home-assistant
      homepage.href: &url https://home-assistant.nicholaslyz.com
      homepage.siteMonitor: *url
    cap_add:
      - net_admin # Allow HA to discover devices on the network

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt@sha256:2a21bbf7a664a149024bbe1f776e3151f28ed9db15948270dcbffb89544a41f0
    restart: always
    user: 1000:1000
    networks:
      - zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: core_zigbee2mqtt
      traefik.http.routers.zigbee2mqtt.rule: Host(`zigbee2mqtt.internal.nicholaslyz.com`)
      traefik.http.routers.zigbee2mqtt.entrypoints: tailscale
      homepage.group: Services
      homepage.name: Zigbee2MQTT
      homepage.icon: zigbee2mqtt
      homepage.href: https://zigbee2mqtt.internal.nicholaslyz.com
      homepage.siteMonitor: http://zigbee2mqtt:8080

  mosquitto:
    image: eclipse-mosquitto@sha256:9cfdd46ad59f3e3e5f592f6baf57ab23e1ad00605509d0f5c1e9b179c5314d87
    container_name: mosquitto
    restart: always
    user: 1000:1000
    networks:
      - zigbee2mqtt
      - home-assistant
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data

networks:
  home-assistant:
  home-assistant-macvlan:
    # Required for device discovery
    # ipvlan does not support DHCP
    driver: macvlan
    driver_opts:
      parent: enp5s0
  zigbee2mqtt:
