services:
  hindsight:
    image: ghcr.io/vectorize-io/hindsight:latest@sha256:84ab276b8f501546deb6ea9c64a57291718b4e16a59dd9e02a02fdd5adfe9028
    container_name: hindsight
    restart: always
    shm_size: 1g
    environment:
      TZ: Asia/Singapore
      HINDSIGHT_API_LLM_API_KEY: ${HINDSIGHT_API_LLM_API_KEY}
      HINDSIGHT_API_LLM_PROVIDER: openrouter
      HINDSIGHT_API_LLM_MODEL: deepseek/deepseek-v4-flash
      HINDSIGHT_API_WORKER_ID: hindsight
      HINDSIGHT_API_LLM_EXTRA_BODY: '{"provider": {"order": ["deepseek"]}}'
    volumes:
      - ./data/hindsight:/home/hindsight/.pg0
    networks:
      - hindsight
    labels:
      traefik.enable: true
      traefik.http.routers.hindsight.rule: Host(`hindsight.internal.nicholaslyz.com`)
      traefik.http.routers.hindsight.entrypoints: tailscale
      traefik.http.services.hindsight.loadbalancer.server.port: 9999
      traefik.docker.network: core_hindsight
      homepage.group: Services
      homepage.name: Hindsight
      homepage.icon: hindsight
      homepage.href: &url https://hindsight.internal.nicholaslyz.com
      homepage.siteMonitor: *url

  hermes-agent-xiaoyun:
    image: nousresearch/hermes-agent@sha256:20c5941469d60ea80ae5ccccffff62c2b2e2c7a0151af46182f464b6050838d6
    container_name: hermes-agent-xiaoyun
    restart: always
    command: gateway run
    depends_on:
      - hindsight
    networks:
      - hermes-agent-xiaoyun
      - open-webui
      - hindsight
    volumes:
      - ./data/xiaoyun:/opt/data
      - ./config.yaml:/opt/data/config.yaml
    environment:
      HERMES_DASHBOARD: 1
      HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ${HERMES_DASHBOARD_BASIC_AUTH_USERNAME}
      HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD}
      HERMES_UID: 1000
      HERMES_GID: 1000
    labels:
      traefik.enable: true
      traefik.http.routers.hermes-agent-xiaoyun.rule: Host(`hermes-agent-xiaoyun.internal.nicholaslyz.com`)
      traefik.http.routers.hermes-agent-xiaoyun.entrypoints: tailscale
      traefik.http.services.hermes-agent-xiaoyun.loadbalancer.server.port: 9119
      traefik.docker.network: core_hermes-agent-xiaoyun
      homepage.group: Services
      homepage.name: Hermes Agent (Xiao Yun)
      homepage.icon: hermesagent
      homepage.href: &url https://hermes-agent-xiaoyun.internal.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  hindsight:
  hermes-agent-xiaoyun:
