model:
  provider: openrouter
  default: &default z-ai/glm-5.3-flash
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions
fallback_providers:
  - provider: openrouter
    model: *default
    base_url: https://openrouter.ai/api/v1
    api_mode: chat_completions
cron:
  model: *default
  model_provider: openrouter
  wrap_response: false
web:
  search_backend: tavily
  extract_backend: tavily
checkpoints:
  delete_orphans: true
display:
  memory_notifications: false
  busy_input_mode: steer
  show_reasoning: false
  streaming: true
  tool_progress: false
  cleanup_progress: true
  interim_assistant_messages: false
  long_running_notifications: false
  busy_ack_detail: false
  busy_ack_enabled: false
  background_process_notifications: false
stt:
  provider: openai
  openai:
    model: gpt-transcribe
memory:
  provider: hindsight
timezone: Asia/Singapore
whatsapp:
  require_mention: false
  extra:
    group_policy: allowlist
    group_allow_from:
      - 6598795366-1372771767@g.us
      - 120363422641179682@g.us
      - 120363410218408492@g.us
telegram:
  require_mention: false
  extra:
    rich_messages: true
command_allowlist:
  - script execution via heredoc
  - script execution via -e/-c flag
streaming:
  enabled: true
group_sessions_per_user: false
platform_toolsets:
  telegram:
    - hermes-cli
  whatsapp:
    - hermes-cli
image_gen:
  provider: openai
  use_gateway: false
  model: gpt-image-2-medium
platforms:
  whatsapp:
    enabled: true
_config_version: 39
onboarding:
  seen:
    busy_input_prompt: true
agent: {}
security:
  redact_secrets: false
approvals:
  destructive_slash_confirm: false
gateway:
  platforms:
    telegram:
      gateway_restart_notification: false
    whatsapp:
      gateway_restart_notification: false
      typing_indicator: false
session_reset:
  mode: both
  idle_minutes: 1440
  at_hour: 4
