services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin@sha256:baba630419915985442f315f08b0cf46d9f4c8a0cc4bd38e94a6d35751dd5ef5
    restart: always
    user: 1000:1000
    volumes:
      - ./data/config:/config
      - ./data/cache:/cache
      - /mnt/storage/Videos:/media
    environment:
      JELLYFIN_PublishedServerUrl: https://jellyfin.nicholaslyz.com
      NVIDIA_VISIBLE_DEVICES: all
    networks:
      - jellyfin
    devices:
      - nvidia.com/gpu=all
    labels:
      traefik.enable: true
      traefik.docker.network: core_jellyfin
      homepage.group: Services
      homepage.name: Jellyfin
      homepage.icon: jellyfin
      homepage.href: &url https://jellyfin.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: jellyfin
      homepage.widget.url: *url
      homepage.widget.key: ${HOMEPAGE_KEY}
      homepage.widget.enableBlocks: true # optional, defaults to false
      homepage.widget.enableNowPlaying: false

networks:
  jellyfin:
