services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux@sha256:8810dfe7f4d9979f9dc1385607695c116f049daa586c635a9a1fb3c58936b074
    restart: always
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
    networks:
      - miniflux
    labels:
      traefik.enable: true
      traefik.docker.network: core_miniflux
      homepage.group: Services
      homepage.name: Miniflux
      homepage.icon: miniflux
      homepage.href: &url https://miniflux.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: miniflux
      homepage.widget.url: *url
      homepage.widget.key: ${HOMEPAGE_KEY}
  miniflux-db:
    container_name: miniflux-db
    image: postgres:18@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    restart: always
    networks:
      - miniflux
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  miniflux:
