services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
    restart: always
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
    networks:
      - miniflux
    labels:
      traefik.enable: true
      traefik.docker.network: core_miniflux
      homepage.group: Services
      homepage.name: Miniflux
      homepage.icon: miniflux
      homepage.href: &url https://miniflux.nicholaslyz.com
      homepage.siteMonitor: *url
      homepage.widget.type: miniflux
      homepage.widget.url: *url
      homepage.widget.key: ${HOMEPAGE_KEY}
  miniflux-db:
    container_name: miniflux-db
    image: postgres:18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    restart: always
    networks:
      - miniflux
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  miniflux:
