services:
  glance:
    container_name: glance
    image: glanceapp/glance@sha256:9dfb09470b207dcb67ac715994bdb1929374ba3f9c0d7df7462c24adf10fd073
    restart: always
    networks:
      - glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.http.routers.glance.rule: Host(`glance.nicholaslyz.com`)
      traefik.enable: true
      traefik.docker.network: core_glance
      homepage.group: Services
      homepage.name: Glance
      homepage.icon: glance
      homepage.href: &url https://glance.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  glance:
