services:
  glance:
    container_name: glance
    image: glanceapp/glance@sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350
    restart: always
    networks:
      - glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.http.routers.glance.rule: Host(`glance.nicholaslyz.com`)
      traefik.enable: true
      traefik.docker.network: core_glance
      homepage.group: Services
      homepage.name: Glance
      homepage.icon: glance
      homepage.href: &url https://glance.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  glance:
