services:
  changedetection-io:
    container_name: changedetection-io
    image: dgtlmoon/changedetection.io@sha256:096dae27b5d677b89f0e810fff95a70403271aa3ff3b6437952d2db9be7e74c5
    restart: always
    volumes:
      - ./data:/datastore
    environment:
      PLAYWRIGHT_DRIVER_URL: ${PLAYWRIGHT_DRIVER_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.changedetection-io.rule: Host(`changedetection-io.internal.nicholaslyz.com`)
      traefik.http.routers.changedetection-io.entrypoints: tailscale
      traefik.docker.network: core_changedetection-io
      homepage.group: Services
      homepage.name: Changedetection.io
      homepage.icon: changedetection
      homepage.href: &url https://changedetection-io.internal.nicholaslyz.com
      homepage.siteMonitor: *url
    networks:
      - changedetection-io

networks:
  changedetection-io:
