services:
  homepage:
    image: ghcr.io/gethomepage/homepage@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    container_name: homepage
    restart: always
    depends_on:
      - homepage-socket-proxy
    networks: # Allow widgets to update via API calls
      - changedetection-io
      - ddns-updater
      - homepage
      - prometheus
      - qbittorrent
      - scrutiny
      - stirling-pdf
      - syncthing
      - unifi
      - zigbee2mqtt
    volumes:
      - ./config:/app/config
      - ./bg.jpg:/app/public/images/bg.jpg:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.internal.nicholaslyz.com
      LOG_TARGETS: stdout
    user: 1000:1000
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`homepage.internal.nicholaslyz.com`)
      traefik.http.routers.homepage.entrypoints: tailscale
      traefik.docker.network: core_homepage

  homepage-socket-proxy:
    restart: always
    container_name: homepage-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    networks:
      - homepage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1

# Traefik can't discover containers using network_mode: service
# https://community.traefik.io/t/docker-compose-with-network-mode-service-service-name/3395/3
networks:
  homepage:
