services:
  paperless-redis:
    image: docker.io/library/redis:8@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
    restart: always
    volumes:
      - paperless-redis:/data
    networks:
      - paperless
  paperless-db:
    image: docker.io/library/postgres:18@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    networks:
      - paperless
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
    restart: always
    depends_on:
      - paperless-redis
      - paperless-db
      - paperless-gotenberg
      - paperless-tika
    networks:
      - paperless
    volumes:
      - ./data/paperless:/usr/src/paperless/data
      - /mnt/storage/Documents:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/storage/Incoming Scans:/usr/src/paperless/consume
    environment:
      DEBUG: true
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_URL: https://paperless.nicholaslyz.com
    labels:
      traefik.enable: true
      traefik.docker.network: core_paperless
      homepage.group: Services
      homepage.name: Paperless
      homepage.icon: paperless-ngx
      homepage.href: &url https://paperless.nicholaslyz.com
      homepage.siteMonitor: *url
  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.34@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
    restart: always
    # The gotenberg chromium route is used to convert .eml files. We do not want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless
  paperless-tika:
    image: docker.io/apache/tika:latest@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
    restart: always
    networks:
      - paperless

volumes:
  paperless-redis:

networks:
  paperless:
