services:
  paperless-redis:
    image: docker.io/library/redis:8
    restart: always
    volumes:
      - paperless-redis:/data
    networks:
      - paperless
  paperless-db:
    image: docker.io/library/postgres:18
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    networks:
      - paperless
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - paperless-redis
      - paperless-db
      - paperless-gotenberg
      - paperless-tika
    networks:
      - paperless
    volumes:
      - ./data/paperless:/usr/src/paperless/data
      - /mnt/storage/Documents:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/storage/Incoming Scans:/usr/src/paperless/consume
    environment:
      DEBUG: true
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_URL: https://paperless.nicholaslyz.com
    labels:
      traefik.enable: true
      traefik.docker.network: core_paperless
      homepage.group: Services
      homepage.name: Paperless
      homepage.icon: paperless-ngx
      homepage.href: &url https://paperless.nicholaslyz.com
      homepage.siteMonitor: *url
  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    restart: always
    # The gotenberg chromium route is used to convert .eml files. We do not want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless
  paperless-tika:
    image: docker.io/apache/tika:latest
    restart: always
    networks:
      - paperless

volumes:
  paperless-redis:

networks:
  paperless:
