services:
  ddns-updater:
    container_name: ddns-updater
    image: qmcgaw/ddns-updater@sha256:dd0d029b8ed74062d53c3a42e147462598600e842b6d08d8cd809b5ab41869e1
    restart: always
    volumes:
      - ./data:/updater/data
    environment:
      TZ: Asia/Singapore
    networks:
      - ddns-updater
    labels:
      traefik.enable: true
      traefik.docker.network: core_ddns-updater
      traefik.http.routers.ddns-updater.rule: Host(`ddns-updater.internal.nicholaslyz.com`)
      traefik.http.routers.ddns-updater.entrypoints: tailscale
      homepage.group: Services
      homepage.name: DDNS Updater
      homepage.icon: ddns-updater
      homepage.href: &url https://ddns-updater.internal.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  ddns-updater:
