services:
  ddns-updater:
    container_name: ddns-updater
    image: qmcgaw/ddns-updater@sha256:d63829b761ba45e37fc8273de722c5f3bdc65d2196e8dd8195406969eb657543
    restart: always
    volumes:
      - ./data:/updater/data
    environment:
      TZ: Asia/Singapore
    networks:
      - ddns-updater
    labels:
      traefik.enable: true
      traefik.docker.network: core_ddns-updater
      traefik.http.routers.ddns-updater.rule: Host(`ddns-updater.internal.nicholaslyz.com`)
      traefik.http.routers.ddns-updater.entrypoints: tailscale
      homepage.group: Services
      homepage.name: DDNS Updater
      homepage.icon: ddns-updater
      homepage.href: &url https://ddns-updater.internal.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  ddns-updater:
