services:
  ddns-updater:
    container_name: ddns-updater
    image: qmcgaw/ddns-updater@sha256:e5e08e006ffd78c4ce88b05d5936e0544d823f94388fa68455d6c9861a76397b
    restart: always
    volumes:
      - ./data:/updater/data
    environment:
      TZ: Asia/Singapore
    networks:
      - ddns-updater
    labels:
      traefik.enable: true
      traefik.docker.network: core_ddns-updater
      traefik.http.routers.ddns-updater.rule: Host(`ddns-updater.internal.nicholaslyz.com`)
      traefik.http.routers.ddns-updater.entrypoints: tailscale
      homepage.group: Services
      homepage.name: DDNS Updater
      homepage.icon: ddns-updater
      homepage.href: &url https://ddns-updater.internal.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  ddns-updater:
