services:
  actualbudget:
    container_name: actualbudget
    image: ghcr.io/actualbudget/actual-server@sha256:74385f8067f401e61f0be9e343c471705c42dfaa195295c40c5b2f15f4dcc9d4
    restart: always
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./data:/data
    networks:
      - actualbudget
    labels:
      traefik.enable: true
      traefik.docker.network: core_actualbudget
      homepage.group: Services
      homepage.name: Actual Budget
      homepage.icon: actual-budget
      homepage.href: &url https://actualbudget.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  actualbudget:
