services:
  actualbudget:
    container_name: actualbudget
    image: ghcr.io/actualbudget/actual-server@sha256:e18b7fbfec6157a368fad4146563f397502e9da70a120aeaeac63b4977405d1c
    restart: always
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./data:/data
    networks:
      - actualbudget
    labels:
      traefik.enable: true
      traefik.docker.network: core_actualbudget
      homepage.group: Services
      homepage.name: Actual Budget
      homepage.icon: actual-budget
      homepage.href: &url https://actualbudget.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  actualbudget:
