services:
  actualbudget:
    container_name: actualbudget
    image: ghcr.io/actualbudget/actual-server@sha256:24645e971da6bb1a1f953d6859e307a0b29be1e8b4130a35b3220c209b5b860c
    restart: always
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./data:/data
    networks:
      - actualbudget
    labels:
      traefik.enable: true
      traefik.docker.network: core_actualbudget
      homepage.group: Services
      homepage.name: Actual Budget
      homepage.icon: actual-budget
      homepage.href: &url https://actualbudget.nicholaslyz.com
      homepage.siteMonitor: *url

networks:
  actualbudget:
